export default [
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'men',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'men',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'men',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'men',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'men',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'women',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'women',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'women',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'women',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'women',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'children',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'children',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'children',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'children',
    },
    {
        sizes: ['xl', 'l', 'm', 's'],
        colors: ['red', 'white'],
        description: '',
        name: 't-shirt',
        price: 5,
        imageURL: '',
        type: 'children',
    },
];
