const initialState = [
    {
        name: 'man',
        visible: true,
        products: [
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 't-shirt',
                price: 5,
                imageURL: '../public/images/Layer 1.jpg',
                type: 'man',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 'backpack',
                price: 60,
                imageURL: '../public/images/Livello 4.jpg',
                type: 'man',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 'pants forclaz',
                price: 30,
                imageURL: '../public/images/Livello 3.jpg',
                type: 'man',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 'giacket',
                price: 60,
                imageURL: '../public/images/Livello 5.jpg',
                type: 'man',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 'tracking shoes',
                price: 80,
                imageURL: '../public/images/Livello 6.jpg',
                type: 'man',
            },
        ],
    },
    {
        name: 'woman',
        visible: true,
        products: [
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 'giacket',
                price: 60,
                imageURL: '../public/images/Livello 5.jpg',
                type: 'woman',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 'tracking shoes',
                price: 80,
                imageURL: '../public/images/Livello 6.jpg',
                type: 'woman',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 't-shirt',
                price: 20,
                imageURL: '../public/images/Livello 7.jpg',
                type: 'woman',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 'backpack',
                price: 60,
                imageURL: '../public/images/Livello 4.jpg',
                type: 'woman',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 'pants',
                price: 30,
                imageURL: '../public/images/Livello 3.jpg',
                type: 'woman',
            },
        ],
    },
    {
        name: 'children',
        visible: false,
        products: [
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 't-shirt',
                price: 5,
                imageURL: '',
                type: 'children',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 't-shirt',
                price: 5,
                imageURL: '',
                type: 'children',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 't-shirt',
                price: 5,
                imageURL: '',
                type: 'children',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 't-shirt',
                price: 5,
                imageURL: '',
                type: 'children',
            },
            {
                sizes: ['xl', 'l', 'm', 's'],
                colors: ['red', 'white'],
                description: '',
                name: 't-shirt',
                price: 5,
                imageURL: '',
                type: 'children',
            },
        ],
    },
];

export default initialState;
